- hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - vars/vcenter-logins.yml

  pre_tasks:
    - import_tasks: tasks/validate-inputs.yml
      tags:
        - always

    - name: Fail if vmware_vm_name is not provided with vm tag
      fail:
        msg: '-e vmware_vm_name=VM is required when --tags vm is used'
      when:
        - "'vm' in ansible_run_tags"
        - (vmware_vm_name is not defined or vmware_vm_name|length == 0)
      tags:
        - always

  tasks:
    - name: Retrieve specific VM information
      vmware_guest_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        name: '{{ vmware_vm_name }}'
        datacenter: '{{ vmware_vm_datacenter }}'
        schema: summary
      register: vm_info
      tags:
        - vm
        - never

    - debug:
        var: vm_info
      tags:
        - vm
        - never

    - name: Retrieve datacenter information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: datacenter
      register: datacenter_listing
      tags:
        - datacenter

    - debug:
        var: datacenter_listing
      tags:
        - datacenter

    - name: Retrieve cluster information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: cluster
      register: cluster_listing
      tags:
        - cluster

    - debug:
        var: cluster_listing
      tags:
        - cluster

    - name: Retrieve datastore information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: datastore
      register: datastore_listing
      tags:
        - datastore

    - debug:
        var: datastore_listing
      tags:
        - datastore

    - name: Retrieve folder information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: folder
      register: folder_listing
      tags:
        - folder

    - debug:
        var: folder_listing
      tags:
        - folder

    - name: Retrieve resource pool information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: resource_pool
      register: resource_pool_listing
      tags:
        - rpool

    - debug:
        var: resource_pool_listing
      tags:
        - rpool

    - name: Retrieve network information
      vmware_objectlist_info:
        hostname: '{{ vcenter_hostname }}'
        username: '{{ vcenter_username }}'
        password: '{{ vcenter_password }}'
        validate_certs: '{{ vcenter_validate_certs }}'
        type: network
      register: network_listing
      tags:
        - network

    - debug:
        var: network_listing
      tags:
        - network
